<?php
return [
    'do_not_encrypt' => [
        'email',
        'first_name',
        'last_name',
        'company_name',
        'company_id',
        'company_unique_id',
        'created_at',
        'updated_at',
        'suburb_name',
        'user_id',
        'country',
        'country_code',
        'password_confirmation',
        'password',
        'email_verified_at',
        'locked',
        'created_at',
        'updated_at',
        'id',
        'town_name',
        'zip_code',
        'town_id',
        'country_id',
        'province_id',
        'suburb_id',
        'province_name',
        'area_code_id',
        'country_name',
        'dial_code',
        'intermediate_region_code',
        'sub_region_code',
        'region_code',
        'intermediate_region',
        'sub_region',
        'region',
        'iso_3166_2',
        'country_code',
        'alpha_3',
        'alpha_2',
        'address_type',
        'role_id',
        'role_name',
        'branch_id',
        'branch_name',
        'branch_unique_id',
        'rule_category_name',
        'affordability_category_name',
        'sub_category_name',
        'credit_report_source',
        'created_by',
        'application_id',
        'loan_cat_id',

    ],
    'models' => [
        'user' => '\App\Models\User',
        'company' => '\App\Models\Company\Company',
        'company_details' => '\App\Models\Company\CompanyDetails',
        'company_billing_details' => '\App\Models\Company\CompanyBillingDetails',
        'suburb' => '\App\Models\Address\Suburb',
        'address' => '\App\Models\Address\Address',
        'country' => '\App\Models\Address\Country',
        'province' => '\App\Models\Address\Province',
        'town' => '\App\Models\Address\Town',
        'area_code' => '\App\Models\Address\AreaCode',
        'user_role' => '\App\Models\UserModels\UserRole',
        'user_company' => '\App\Models\UserModels\UserCompany',
        'role' => '\App\Models\UserModels\Role',
        'branch' => '\App\Models\Branch\Branch',
        'branch_details' => '\App\Models\Branch\BranchDetails',
        'user_branch' => '\App\Models\Branch\UserBranch',
        'user_permission' => '\App\Models\UserModels\UserPermissions',
        'company_staff' => '\App\Models\Company\CompanyStaff',
        'rule_category' => '\App\Models\Categories\RuleCategory',
        'rule_sub_category' => '\App\Models\Categories\RuleSubCategory',
        'system_rule' => '\App\Models\Rules\SystemRule',
        'system_rule_answer' => '\App\Models\Rules\SystemRuleAnswer',
        'loan_application' => '\App\Models\LoanWizard\LoanApplication',
        'personal_details' => '\App\Models\LoanWizard\PersonalDetail',
        'system_user' => '\App\Models\LoanWizard\SystemUser',
        'credit_report_data' => '\App\Models\CreditReport\CreditReportData',
        'branch_settings' => '\App\Models\Branch\BranchSettings',
        'employment_information' => '\App\Models\LoanWizard\EmploymentInformation',
    ],
    'steps' => [
        'training-check' => [
            'currentStep' => false,
            'progress' => 0,
            'title' => 'Application Start',
        ],
        'personal-information' => [
            'currentStep' => 0,
            'progress' => 10,
            'title' => 'Personal information',
        ],
        'employment-details' => [
            'currentStep' => 1,
            'progress' => 15,
            'title' => 'Employment details',
        ],

    ]
];
